# Generated by Django 5.1.3 on 2024-12-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set',
            new_name='Sett',
        ),
    ]
