# Generated by Django 5.1.3 on 2024-12-04 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w', '0002_rename_set_sett'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetMeister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reps', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_meister', to='w.workout')),
            ],
        ),
        migrations.DeleteModel(
            name='Sett',
        ),
    ]
