/**
 * Workout Tracker API
 * API documentation for workout tracker
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@workouttracker.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Exercise { 
    readonly id?: number;
    name: string;
    muscle_group?: string | null;
    description?: string | null;
}

