/**
 * Workout Tracker API
 * API documentation for workout tracker
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@workouttracker.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Cardio } from './cardio';


export interface Workout { 
    readonly id?: number;
    user: number;
    readonly date_created?: Date;
    notes?: string | null;
    readonly sets?: Array<Set>;
    readonly cardio_sessions?: Array<Cardio>;
}

