/**
 * Workout Tracker API
 * API documentation for workout tracker
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@workouttracker.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Cardio { 
    readonly id?: number;
    cardio_type: string;
    duration: string;
    distance?: string | null;
    workout: number;
}

