/**
 * Workout Tracker API
 * API documentation for workout tracker
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@workouttracker.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Exercise } from './exercise';


export interface SetMeister { 
    readonly id?: number;
    exercise: Exercise;
    weight: string;
    reps: number;
    workout: number;
}

